directories:
  output: dist
  buildResources: assets
extends: null
appId: com.example.electron-cra
files:
  - filter:
      - dist/**/*
      - build/**/*
      - node_moudles/**/*
      - package.json
extraMetadata:
  main: build/main.js
electronVersion: 19.0.6
